<template>
  <div class="reports-list">
    <h2 class="reports-list__title">Available Reports</h2>
    <div class="reports-list__card">
      <div
        v-for="report in reports"
        :key="report.id"
        class="reports-list__row"
      >
        <!-- Icon -->
        <div class="reports-list__icon-wrap">
          <i :class="report.icon" />
        </div>

        <!-- Name + description -->
        <div class="reports-list__col reports-list__col--name">
          <span class="reports-list__primary">{{ report.name }}</span>
          <span class="reports-list__secondary">{{ report.description }}</span>
        </div>

        <!-- Generated by -->
        <div class="reports-list__col">
          <span class="reports-list__primary">{{ report.generatedBy }}</span>
          <span class="reports-list__secondary">Generated by</span>
        </div>

        <!-- Frequency -->
        <div class="reports-list__col">
          <span class="reports-list__primary">{{ report.frequency }}</span>
          <span class="reports-list__secondary">Frequency</span>
        </div>

        <!-- Last generated -->
        <div class="reports-list__col">
          <span class="reports-list__primary">{{ report.lastGenerated }}</span>
          <span class="reports-list__secondary">Last Generated</span>
        </div>

        <!-- Actions -->
        <div class="reports-list__actions">
          <button
            class="reports-list__btn reports-list__btn--details"
            @click="openDetails(report)"
          >
            View Details
          </button>
          <button
            class="reports-list__btn reports-list__btn--export"
            @click="exportReport(report)"
          >
            <i class="pi pi-download" />
            Export
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Details Dialog -->
  <Dialog
    v-model:visible="detailsDialog"
    modal
    :style="{ width: '460px' }"
  >
    <template #header>
      <div class="report-dialog__header">
        <div class="report-dialog__icon-wrap">
          <i :class="selectedReport?.icon" />
        </div>
        <span class="report-dialog__title">{{ selectedReport?.name }}</span>
      </div>
    </template>

    <div v-if="selectedReport" class="report-dialog">
      <p class="report-dialog__description">{{ selectedReport.details }}</p>

      <div class="report-dialog__grid">
        <div class="report-dialog__item">
          <span class="report-dialog__item-label">Generated by</span>
          <span class="report-dialog__item-value">{{ selectedReport.generatedBy }}</span>
        </div>
        <div class="report-dialog__item">
          <span class="report-dialog__item-label">Frequency</span>
          <span class="report-dialog__item-value">{{ selectedReport.frequency }}</span>
        </div>
        <div class="report-dialog__item">
          <span class="report-dialog__item-label">Last Generated</span>
          <span class="report-dialog__item-value">{{ selectedReport.lastGenerated }}</span>
        </div>
        <div class="report-dialog__item">
          <span class="report-dialog__item-label">Format</span>
          <span class="report-dialog__item-value">PDF</span>
        </div>
      </div>
    </div>

    <template #footer>
      <Button
        label="Close"
        severity="secondary"
        text
        @click="detailsDialog = false"
      />
      <Button
        label="Export PDF"
        icon="pi pi-download"
        @click="exportReport(selectedReport!)"
      />
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import Dialog from 'primevue/dialog'
import Button from 'primevue/button'
import { getReports } from '@/services/dashboardService'

type Report = {
  id: number
  name: string
  description: string
  generatedBy: string
  frequency: string
  lastGenerated: string
  icon: string
  details: string
}

const reports = ref<Report[]>([])
const detailsDialog = ref(false)
const selectedReport = ref<Report | null>(null)

onMounted(async () => {
  reports.value = await getReports()
})

function openDetails(report: Report) {
  selectedReport.value = report
  detailsDialog.value = true
}

function exportReport(report: Report) {
  // Will be replaced with real PDF generation
  console.log(`Exporting ${report.name} as PDF`)
  alert(`Exporting "${report.name}" as PDF — connect to your PDF service here.`)
}
</script>

<style scoped src="@/assets/reports/ReportsList.css" />